### ISSUE TITLE
Transfer domain to Golang Vietnam community

### ISSUE THREAD

**Issue by plutov** [golang-vietnam/gophercon-landing#5]
As you may know, currently I own the domain gophercon.vn and it will expire soon. The registrar is vinahost.vn

Let me know how can I transfer it to Golang Vietnam?

<img width="871" alt="Screen Shot 2019-07-12 at 9 12 20 AM" src="https://user-images.githubusercontent.com/1124859/61109478-42cf5380-a485-11e9-8ed8-86bdd6e69e39.png">

**Comment by tieubao** [comment]
Thanks @plutov. I have completed the transfer
